// apps/angular-demo/src/app/app.component.ts
import { Component, computed, inject, signal } from '@angular/core';
import { Location } from '@angular/common';
import { HybridSignHostComponent } from './hybrid-sign-host.component';
import type { TenantId, Language, SessionEndEvent } from '@hs/lib';
import { API_ENDPOINT, InitService } from './init.service';
import {
  buildSessionPath,
  readSessionFromLocation,
  type SessionUrlState,
} from './session-url';

const INVALID_FILE_MESSAGE = 'Molimo izaberite PDF fajl.';
const TENANT_IDS: readonly TenantId[] = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
];
const LANGUAGES: readonly Language[] = ['en', 'de'];

function isPdfFile(candidate: File): boolean {
  if (candidate.type) {
    return candidate.type === 'application/pdf';
  }
  return candidate.name.toLowerCase().endsWith('.pdf');
}

function isValidEmail(value: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}

@Component({
  selector: 'app-root',
  imports: [HybridSignHostComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  private readonly initService = inject(InitService);
  private readonly location = inject(Location);

  protected readonly tenantIds = TENANT_IDS;
  protected readonly languages = LANGUAGES;
  protected readonly apiEndpoint = API_ENDPOINT;

  protected readonly signatureFlow = signal(false);
  protected readonly email = signal('');
  protected readonly note = signal('');
  protected readonly emailTouched = signal(false);
  protected readonly isUploading = signal(false);
  protected readonly uploadError = signal<string | null>(null);
  protected readonly tenantId = signal<TenantId>('1');
  protected readonly language = signal<Language>('en');
  // Session identity lives on the URL (`/session?transactionId=&sk=`), same
  // as `_standalone`'s session-create → session-sign navigation — refresh
  // and invitation links reopen the viewer without re-uploading.
  protected readonly session = signal<SessionUrlState | null>(
    readSessionFromLocation(),
  );
  protected readonly sessionEndEvent = signal<SessionEndEvent | null>(null);

  constructor() {
    this.applyFromUrl();
    this.location.subscribe(() => this.applyFromUrl());
  }

  private applyFromUrl(): void {
    const parsed = readSessionFromLocation();
    this.session.set(parsed);
    if (parsed) {
      this.tenantId.set(parsed.tenantId);
      this.language.set(parsed.language);
    } else {
      this.sessionEndEvent.set(null);
    }
  }

  private goToSession(next: SessionUrlState): void {
    this.location.go(buildSessionPath(next));
    this.applyFromUrl();
  }

  private goHome(): void {
    this.location.go('/');
    this.applyFromUrl();
  }

  protected readonly canUpload = computed(
    () => !this.signatureFlow() || isValidEmail(this.email()),
  );
  protected readonly showEmailRequired = computed(
    () =>
      this.signatureFlow() && this.emailTouched() && this.email().trim() === '',
  );
  protected readonly showEmailInvalid = computed(
    () =>
      this.signatureFlow() &&
      this.emailTouched() &&
      this.email().trim() !== '' &&
      !isValidEmail(this.email()),
  );

  protected selectTenant(id: TenantId): void {
    this.tenantId.set(id);
  }

  protected selectLanguage(code: Language): void {
    this.language.set(code);
  }

  protected onSessionEnd(event: SessionEndEvent): void {
    // Standalone's default handler: cancel navigates back to `/`.
    // Finalize/workflow/remote stay on the session URL and show the matching
    // lib endscreen.
    if (event.reason === 'Canceled') {
      this.goHome();
      return;
    }
    this.sessionEndEvent.set(event);
  }

  protected onSignatureFlowChange(event: Event): void {
    const checked = (event.target as HTMLInputElement).checked;
    this.signatureFlow.set(checked);
    if (checked) {
      this.emailTouched.set(true);
    } else {
      this.email.set('');
      this.note.set('');
      this.emailTouched.set(false);
    }
  }

  protected onEmailInput(event: Event): void {
    this.email.set((event.target as HTMLInputElement).value);
    this.emailTouched.set(true);
  }

  protected onNoteInput(event: Event): void {
    this.note.set((event.target as HTMLTextAreaElement).value);
  }

  protected onFileChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    void this.takePdf(input.files);
    input.value = '';
  }

  protected onDragOver(event: DragEvent): void {
    event.preventDefault();
  }

  protected onDrop(event: DragEvent): void {
    event.preventDefault();
    void this.takePdf(event.dataTransfer?.files ?? null);
  }

  private async takePdf(files: FileList | null): Promise<void> {
    if (!files?.length || !this.canUpload() || this.isUploading()) {
      return;
    }
    const list = Array.from(files);
    if (list.some((f) => !isPdfFile(f))) {
      this.uploadError.set(INVALID_FILE_MESSAGE);
      return;
    }
    this.uploadError.set(null);
    this.isUploading.set(true);
    try {
      const documents = await this.initService.createSession(
        list,
        this.signatureFlow(),
        this.email(),
        this.note(),
      );
      const first = documents[0];
      this.goToSession({
        transactionId: first.transactionId,
        secretKey: first.secretKey,
        name: list[0].name,
        tenantId: this.tenantId(),
        language: this.language(),
      });
    } catch (err) {
      this.uploadError.set(
        err instanceof Error ? err.message : 'Unbekannter Fehler',
      );
    } finally {
      this.isUploading.set(false);
    }
  }
}

@if (session(); as entry) {
  <div class="viewer-overlay">
    <app-hybrid-sign-host
      [tenantId]="entry.tenantId"
      [language]="entry.language"
      [transactionId]="entry.transactionId"
      [secretKey]="entry.secretKey"
      [signee]="entry.signee"
      [apiEndpoint]="apiEndpoint"
      [sessionEndEvent]="sessionEndEvent()"
      (sessionEnd)="onSessionEnd($event)"
    />
  </div>
} @else {
  <div class="page">
    <header class="header">
      <div class="header__navigation">
        <a class="header__logo" href="https://www.post.at">
          <img src="post-horn.svg" alt="Österreichische Post" />
        </a>
        <div class="header__controls">
          <div class="header__tenant-select" role="group" aria-label="Tenant">
            @for (id of tenantIds; track id) {
              <button
                type="button"
                disabled
                class="header__tenant-button"
                [class.header__tenant-button--active]="id === tenantId()"
                [attr.aria-pressed]="id === tenantId()"
                (click)="selectTenant(id)"
              >
                Tenant {{ id }}
              </button>
            }
          </div>
          <div
            class="header__language-select"
            role="group"
            aria-label="Language"
          >
            @for (code of languages; track code) {
              <button
                type="button"
                disabled
                class="header__language-button"
                [class.header__language-button--active]="code === language()"
                [attr.aria-pressed]="code === language()"
                (click)="selectLanguage(code)"
              >
                {{ code.toUpperCase() }}
              </button>
            }
          </div>
        </div>
      </div>
    </header>

    <main class="form-wrapper">
      <div class="form-container">
        <h1 class="form-heading">PDF unterschreiben</h1>
        <div class="form-content">
          <div
            class="upload"
            (dragover)="onDragOver($event)"
            (drop)="onDrop($event)"
          >
            <div class="upload__wrapper">
              <div class="upload__icon" aria-hidden="true">
                <svg viewBox="0 0 72 72" width="72" height="72">
                  <rect
                    x="16"
                    y="10"
                    width="40"
                    height="52"
                    rx="3"
                    fill="none"
                    stroke="#0078c8"
                    stroke-width="3"
                  />
                  <path
                    d="M36 28v20M28 36l8-8 8 8"
                    fill="none"
                    stroke="#0078c8"
                    stroke-width="3"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  />
                </svg>
              </div>
              <p class="upload__title">
                {{
                  isUploading()
                    ? 'Wird hochgeladen…'
                    : 'Datei per Drag und Drop ablegen oder'
                }}
              </p>
              <span class="upload__button">Datei auswählen</span>
              <input
                class="upload__file-input"
                type="file"
                accept="application/pdf"
                multiple
                aria-label="Datei auswählen"
                [disabled]="!canUpload() || isUploading()"
                (change)="onFileChange($event)"
              />
            </div>
          </div>
          @if (uploadError()) {
            <p class="email-error">{{ uploadError() }}</p>
          }

          <form class="extras" autocomplete="off" novalidate>
            <div class="checkbox">
              <input
                id="checkbox"
                type="checkbox"
                [checked]="signatureFlow()"
                (change)="onSignatureFlowChange($event)"
              />
              <label for="checkbox">
                Ich will einen Signaturlauf an mehrere Personen versenden.
              </label>
            </div>

            @if (signatureFlow()) {
              <div class="email">
                <label for="email">
                  Bitte geben Sie Ihre E-Mail Adresse ein, auf der Sie das von
                  allen Parteien unterschriebene Dokument empfangen wollen:
                </label>
                <input
                  id="email"
                  type="text"
                  [value]="email()"
                  (input)="onEmailInput($event)"
                />
                @if (showEmailInvalid()) {
                  <p class="email-error">
                    Bitte geben Sie eine gültige E-Mail-Adresse an.
                  </p>
                }
                @if (showEmailRequired()) {
                  <p class="email-error">Pflichtfeld.</p>
                }
              </div>
              <div class="note">
                <label for="note">Notiz:</label>
                <textarea
                  id="note"
                  [value]="note()"
                  (input)="onNoteInput($event)"
                ></textarea>
              </div>
            }
          </form>
        </div>
      </div>
    </main>

    <footer class="footer">
      <div class="footer__item">
        <div class="footer__separator"></div>
        <h2 class="footer__title">HOTLINE: +43 800 2088 23</h2>
        <span class="footer__span">Servicezeiten:</span>
        <span class="footer__span">
          Montag - Donnerstag (werktags): 08:00 - 17:00
        </span>
        <span class="footer__span">Freitag (werktags): 08:00 - 14:00</span>
        <span class="footer__span">
          Support:
          <a href="mailto:servicedesk&#64;sendhybrid.com"
            >servicedesk&#64;sendhybrid.com</a
          >
        </span>
      </div>
    </footer>
  </div>
}

// apps/react-demo/src/App.tsx
import { useEffect, useState } from 'react';
import type { ChangeEvent, DragEvent } from 'react';
import {
  HybridSign,
  SessionFinalizedEndscreen,
  SessionCanceledEndscreen,
  RemoteSignatureEndscreen,
} from '@hs/lib';
import type { TenantId, Language, SessionEndEvent } from '@hs/lib';
import postHorn from './assets/post-horn.svg';
import { createSession } from '../api/init.service';
import {
  buildSessionPath,
  readSessionFromLocation,
  type SessionUrlState,
} from './sessionUrl';
import './App.css';

const INVALID_FILE_MESSAGE = 'Molimo izaberite PDF fajl.';
const TENANT_IDS: TenantId[] = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
];
const LANGUAGES: Language[] = ['en', 'de'];

function isPdfFile(candidate: File): boolean {
  if (candidate.type) {
    return candidate.type === 'application/pdf';
  }
  return candidate.name.toLowerCase().endsWith('.pdf');
}

function isValidEmail(value: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}

// Mirrors legacy's demo app `handleSessionEnd` switch (`pdf-viewer.component.ts`)
// — legacy navigates its own router to a full endscreen route; this demo has
// no router at all, so it just swaps which component is rendered in place.
// That's an internal simplification of the demo harness, not of the library:
// the library still only exposes `onSessionEnd` + the exported screen
// components, exactly like legacy's `sessionEnd` output + exported components.
function renderEndscreen(event: SessionEndEvent) {
  const tenantId = event.tenantId;
  const language = (event.locale || 'en') as Language;
  switch (event.reason) {
    case 'Canceled':
      return (
        <SessionCanceledEndscreen tenantId={tenantId} language={language} />
      );
    case 'Finalized':
    case 'SignatureWorkflow':
      return (
        <SessionFinalizedEndscreen tenantId={tenantId} language={language} />
      );
    case 'RemoteSignatureProcessing':
      return (
        <RemoteSignatureEndscreen
          tenantId={tenantId}
          language={language}
          deliveryChannel={event.deliveryChannel}
        />
      );
  }
}

export default function App() {
  const [signatureFlow, setSignatureFlow] = useState(false);
  const [email, setEmail] = useState('');
  const [note, setNote] = useState('');
  const [emailTouched, setEmailTouched] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [tenantId, setTenantId] = useState<TenantId>('1');
  const [language, setLanguage] = useState<Language>('en');
  // Session identity lives on the URL (`/session?transactionId=&sk=`), same
  // as `_standalone`'s session-create → session-sign navigation — refresh
  // and invitation links reopen the viewer without re-uploading.
  const [session, setSession] = useState<SessionUrlState | null>(
    readSessionFromLocation,
  );
  const [sessionEndEvent, setSessionEndEvent] =
    useState<SessionEndEvent | null>(null);

  useEffect(() => {
    function onPopState() {
      const next = readSessionFromLocation();
      setSession(next);
      if (!next) setSessionEndEvent(null);
    }
    window.addEventListener('popstate', onPopState);
    return () => window.removeEventListener('popstate', onPopState);
  }, []);

  function goToSession(next: SessionUrlState) {
    history.pushState(null, '', buildSessionPath(next));
    setSession(next);
    setSessionEndEvent(null);
  }

  function goHome() {
    history.pushState(null, '', '/');
    setSession(null);
    setSessionEndEvent(null);
  }

  function onSessionEnd(event: SessionEndEvent) {
    // Standalone's default handler: cancel (and anything that isn't
    // finalize/workflow) navigates back to `/`. Finalize/workflow/remote
    // stay on the session URL and show the matching lib endscreen.
    if (event.reason === 'Canceled') {
      goHome();
      return;
    }
    setSessionEndEvent(event);
  }

  const canUpload = !signatureFlow || isValidEmail(email);
  const showEmailRequired =
    signatureFlow && emailTouched && email.trim() === '';
  const showEmailInvalid =
    signatureFlow &&
    emailTouched &&
    email.trim() !== '' &&
    !isValidEmail(email);

  // No review/confirm step: the demo embeds the viewer directly (unlike
  // `_demo_app_reference`, which only kicks off a session and redirects
  // elsewhere), so a valid selection goes straight into `createSession` and
  // on to `<HybridSign>`.
  async function takePdf(files: FileList | null) {
    if (!files?.length || !canUpload || isUploading) {
      return;
    }
    const list = Array.from(files);
    if (list.some((f) => !isPdfFile(f))) {
      setUploadError(INVALID_FILE_MESSAGE);
      return;
    }
    setUploadError(null);
    setIsUploading(true);
    try {
      const documents = await createSession(list, signatureFlow, email, note);
      const first = documents[0];
      goToSession({
        transactionId: first.transactionId,
        secretKey: first.secretKey,
        name: list[0].name,
        tenantId,
        language,
      });
    } catch (err) {
      setUploadError(err instanceof Error ? err.message : 'Unbekannter Fehler');
    } finally {
      setIsUploading(false);
    }
  }

  function onFileChange(event: ChangeEvent<HTMLInputElement>) {
    void takePdf(event.target.files);
    event.target.value = '';
  }

  function onDrop(event: DragEvent<HTMLDivElement>) {
    event.preventDefault();
    void takePdf(event.dataTransfer.files);
  }

  if (session) {
    return (
      <div className="viewer-overlay">
        {sessionEndEvent ? (
          renderEndscreen(sessionEndEvent)
        ) : (
          <HybridSign
            tenantId={session.tenantId}
            language={session.language}
            transactionId={session.transactionId}
            secretKey={session.secretKey}
            signee={session.signee}
            apiEndpoint={import.meta.env.VITE_API_ENDPOINT}
            onSessionEnd={onSessionEnd}
          />
        )}
      </div>
    );
  }

  return (
    <div className="page">
      <header className="header">
        <div className="header__navigation">
          <a className="header__logo" href="https://www.post.at">
            <img src={postHorn} alt="Österreichische Post" />
          </a>
          <div className="header__controls">
            <div
              className="header__tenant-select"
              role="group"
              aria-label="Tenant"
            >
              {TENANT_IDS.map((id) => (
                <button
                  key={id}
                  type="button"
                  disabled
                  className={
                    id === tenantId
                      ? 'header__tenant-button header__tenant-button--active'
                      : 'header__tenant-button'
                  }
                  aria-pressed={id === tenantId}
                  onClick={() => setTenantId(id)}
                >
                  Tenant {id}
                </button>
              ))}
            </div>
            <div
              className="header__language-select"
              role="group"
              aria-label="Language"
            >
              {LANGUAGES.map((code) => (
                <button
                  key={code}
                  type="button"
                  disabled
                  className={
                    code === language
                      ? 'header__language-button header__language-button--active'
                      : 'header__language-button'
                  }
                  aria-pressed={code === language}
                  onClick={() => setLanguage(code)}
                >
                  {code.toUpperCase()}
                </button>
              ))}
            </div>
          </div>
        </div>
      </header>

      <main className="form-wrapper">
        <div className="form-container">
          <h1 className="form-heading">PDF unterschreiben</h1>
          <div className="form-content">
            <div
              className="upload"
              onDragOver={(event) => event.preventDefault()}
              onDrop={onDrop}
            >
              <div className="upload__wrapper">
                <div className="upload__icon" aria-hidden="true">
                  <svg viewBox="0 0 72 72" width="72" height="72">
                    <rect
                      x="16"
                      y="10"
                      width="40"
                      height="52"
                      rx="3"
                      fill="none"
                      stroke="#0078c8"
                      strokeWidth="3"
                    />
                    <path
                      d="M36 28v20M28 36l8-8 8 8"
                      fill="none"
                      stroke="#0078c8"
                      strokeWidth="3"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                </div>
                <p className="upload__title">
                  {isUploading
                    ? 'Wird hochgeladen…'
                    : 'Datei per Drag und Drop ablegen oder'}
                </p>
                <span className="upload__button">Datei auswählen</span>
                <input
                  className="upload__file-input"
                  type="file"
                  accept="application/pdf"
                  multiple
                  aria-label="Datei auswählen"
                  disabled={!canUpload || isUploading}
                  onChange={onFileChange}
                />
              </div>
            </div>
            {uploadError && <p className="email-error">{uploadError}</p>}

            <form className="extras" autoComplete="off" noValidate>
              <div className="checkbox">
                <input
                  id="checkbox"
                  type="checkbox"
                  checked={signatureFlow}
                  onChange={(event) => {
                    setSignatureFlow(event.target.checked);
                    if (event.target.checked) {
                      setEmailTouched(true);
                    } else {
                      setEmail('');
                      setNote('');
                      setEmailTouched(false);
                    }
                  }}
                />
                <label htmlFor="checkbox">
                  Ich will einen Signaturlauf an mehrere Personen versenden.
                </label>
              </div>

              {signatureFlow && (
                <>
                  <div className="email">
                    <label htmlFor="email">
                      Bitte geben Sie Ihre E-Mail Adresse ein, auf der Sie das
                      von allen Parteien unterschriebene Dokument empfangen
                      wollen:
                    </label>
                    <input
                      id="email"
                      type="text"
                      value={email}
                      onChange={(event) => {
                        setEmail(event.target.value);
                        setEmailTouched(true);
                      }}
                    />
                    {showEmailInvalid && (
                      <p className="email-error">
                        Bitte geben Sie eine gültige E-Mail-Adresse an.
                      </p>
                    )}
                    {showEmailRequired && (
                      <p className="email-error">Pflichtfeld.</p>
                    )}
                  </div>
                  <div className="note">
                    <label htmlFor="note">Notiz:</label>
                    <textarea
                      id="note"
                      value={note}
                      onChange={(event) => setNote(event.target.value)}
                    />
                  </div>
                </>
              )}
            </form>
          </div>
        </div>
      </main>

      <footer className="footer">
        <div className="footer__item">
          <div className="footer__separator" />
          <h2 className="footer__title">HOTLINE: +43 800 2088 23</h2>
          <span className="footer__span">Servicezeiten:</span>
          <span className="footer__span">
            Montag - Donnerstag (werktags): 08:00 - 17:00
          </span>
          <span className="footer__span">
            Freitag (werktags): 08:00 - 14:00
          </span>
          <span className="footer__span">
            Support:{' '}
            <a href="mailto:servicedesk@sendhybrid.com">
              servicedesk@sendhybrid.com
            </a>
          </span>
        </div>
      </footer>
    </div>
  );
}
